# Exercise 1


In [1]:
using ITensors

## 1. Matrix Product State

### a. Product MPS

In [2]:
N = 10

sites = siteinds("S=1/2", N)

states = ["Up" for i in 1:N]

psi = productMPS(sites, states)

MPS
[1] ((dim=2|id=276|"S=1/2,Site,n=1"), (dim=1|id=335|"Link,l=1"))
[2] ((dim=1|id=335|"Link,l=1"), (dim=2|id=968|"S=1/2,Site,n=2"), (dim=1|id=956|"Link,l=2"))
[3] ((dim=1|id=956|"Link,l=2"), (dim=2|id=391|"S=1/2,Site,n=3"), (dim=1|id=543|"Link,l=3"))
[4] ((dim=1|id=543|"Link,l=3"), (dim=2|id=327|"S=1/2,Site,n=4"), (dim=1|id=233|"Link,l=4"))
[5] ((dim=1|id=233|"Link,l=4"), (dim=2|id=600|"S=1/2,Site,n=5"), (dim=1|id=16|"Link,l=5"))
[6] ((dim=1|id=16|"Link,l=5"), (dim=2|id=109|"S=1/2,Site,n=6"), (dim=1|id=622|"Link,l=6"))
[7] ((dim=1|id=622|"Link,l=6"), (dim=2|id=941|"S=1/2,Site,n=7"), (dim=1|id=637|"Link,l=7"))
[8] ((dim=1|id=637|"Link,l=7"), (dim=2|id=636|"S=1/2,Site,n=8"), (dim=1|id=521|"Link,l=8"))
[9] ((dim=1|id=521|"Link,l=8"), (dim=2|id=576|"S=1/2,Site,n=9"), (dim=1|id=468|"Link,l=9"))
[10] ((dim=1|id=468|"Link,l=9"), (dim=2|id=350|"S=1/2,Site,n=10"))


In [3]:
expect(psi, "Z")

10-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [4]:
N = 10

sites = siteinds("S=1/2", N)

states = ["Dn" for i in 1:N]

psi = productMPS(sites, states)

MPS
[1] ((dim=2|id=93|"S=1/2,Site,n=1"), (dim=1|id=852|"Link,l=1"))
[2] ((dim=1|id=852|"Link,l=1"), (dim=2|id=595|"S=1/2,Site,n=2"), (dim=1|id=931|"Link,l=2"))
[3] ((dim=1|id=931|"Link,l=2"), (dim=2|id=865|"S=1/2,Site,n=3"), (dim=1|id=720|"Link,l=3"))
[4] ((dim=1|id=720|"Link,l=3"), (dim=2|id=33|"S=1/2,Site,n=4"), (dim=1|id=293|"Link,l=4"))
[5] ((dim=1|id=293|"Link,l=4"), (dim=2|id=311|"S=1/2,Site,n=5"), (dim=1|id=185|"Link,l=5"))
[6] ((dim=1|id=185|"Link,l=5"), (dim=2|id=979|"S=1/2,Site,n=6"), (dim=1|id=761|"Link,l=6"))
[7] ((dim=1|id=761|"Link,l=6"), (dim=2|id=875|"S=1/2,Site,n=7"), (dim=1|id=540|"Link,l=7"))
[8] ((dim=1|id=540|"Link,l=7"), (dim=2|id=854|"S=1/2,Site,n=8"), (dim=1|id=472|"Link,l=8"))
[9] ((dim=1|id=472|"Link,l=8"), (dim=2|id=684|"S=1/2,Site,n=9"), (dim=1|id=48|"Link,l=9"))
[10] ((dim=1|id=48|"Link,l=9"), (dim=2|id=730|"S=1/2,Site,n=10"))


In [5]:
expect(psi, "Z")

10-element Vector{Float64}:
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0
 -1.0

In [6]:
N = 10

sites = siteinds("S=1/2", N)

states = [isodd(n) ? "Up" : "Dn" for n=1:N]

psi = productMPS(sites, states)

MPS
[1] ((dim=2|id=499|"S=1/2,Site,n=1"), (dim=1|id=978|"Link,l=1"))
[2] ((dim=1|id=978|"Link,l=1"), (dim=2|id=631|"S=1/2,Site,n=2"), (dim=1|id=403|"Link,l=2"))
[3] ((dim=1|id=403|"Link,l=2"), (dim=2|id=564|"S=1/2,Site,n=3"), (dim=1|id=528|"Link,l=3"))
[4] ((dim=1|id=528|"Link,l=3"), (dim=2|id=261|"S=1/2,Site,n=4"), (dim=1|id=490|"Link,l=4"))
[5] ((dim=1|id=490|"Link,l=4"), (dim=2|id=128|"S=1/2,Site,n=5"), (dim=1|id=878|"Link,l=5"))
[6] ((dim=1|id=878|"Link,l=5"), (dim=2|id=971|"S=1/2,Site,n=6"), (dim=1|id=865|"Link,l=6"))
[7] ((dim=1|id=865|"Link,l=6"), (dim=2|id=92|"S=1/2,Site,n=7"), (dim=1|id=340|"Link,l=7"))
[8] ((dim=1|id=340|"Link,l=7"), (dim=2|id=644|"S=1/2,Site,n=8"), (dim=1|id=730|"Link,l=8"))
[9] ((dim=1|id=730|"Link,l=8"), (dim=2|id=899|"S=1/2,Site,n=9"), (dim=1|id=936|"Link,l=9"))
[10] ((dim=1|id=936|"Link,l=9"), (dim=2|id=875|"S=1/2,Site,n=10"))


In [7]:
expect(psi, "Z")

10-element Vector{Float64}:
  1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0
  1.0
 -1.0

### b. Random MPS

In [8]:
N = 10

sites = siteinds("S=1/2", N)

rand_psi = randomMPS(sites; linkdims=20)


MPS
[1] ((dim=2|id=433|"S=1/2,Site,n=1"), (dim=20|id=188|"Link,l=1"))
[2] ((dim=20|id=188|"Link,l=1"), (dim=2|id=27|"S=1/2,Site,n=2"), (dim=20|id=965|"Link,l=2"))
[3] ((dim=20|id=965|"Link,l=2"), (dim=2|id=613|"S=1/2,Site,n=3"), (dim=20|id=691|"Link,l=3"))
[4] ((dim=20|id=691|"Link,l=3"), (dim=2|id=307|"S=1/2,Site,n=4"), (dim=20|id=631|"Link,l=4"))
[5] ((dim=20|id=631|"Link,l=4"), (dim=2|id=166|"S=1/2,Site,n=5"), (dim=20|id=912|"Link,l=5"))
[6] ((dim=20|id=912|"Link,l=5"), (dim=2|id=358|"S=1/2,Site,n=6"), (dim=16|id=911|"Link,l=6"))
[7] ((dim=16|id=911|"Link,l=6"), (dim=2|id=680|"S=1/2,Site,n=7"), (dim=8|id=409|"Link,l=7"))
[8] ((dim=8|id=409|"Link,l=7"), (dim=2|id=288|"S=1/2,Site,n=8"), (dim=4|id=704|"Link,l=8"))
[9] ((dim=4|id=704|"Link,l=8"), (dim=2|id=869|"S=1/2,Site,n=9"), (dim=2|id=972|"Link,l=9"))
[10] ((dim=2|id=972|"Link,l=9"), (dim=2|id=246|"S=1/2,Site,n=10"))


In [9]:
linkdims = [dim(linkind(rand_psi, i)) for i in 1:N-1]


9-element Vector{Int64}:
 20
 20
 20
 20
 20
 16
  8
  4
  2

### c. MPS by hand

For example, the generalized GHZ state is
$$\begin{align}
    \ket{GHZ}=\frac{\ket{00...0}+\ket{11...1}}{\sqrt{2}}\,,
\end{align}$$
which can be constructed with open boundary using
$$\begin{align}
    A^{(1)}_0 &= \begin{pmatrix}
        1/\sqrt{2} & 0
    \end{pmatrix}\,,\quad\quad
    A^{(1)}_1 = \begin{pmatrix}
        0 & 1/\sqrt{2}
    \end{pmatrix}\,,\\
    A^{(k)}_0 &= \begin{pmatrix}
        1 & 0\\
        0 & 0
    \end{pmatrix}\,,\quad
    A^{(k)}_1 = \begin{pmatrix}
        0 & 0\\
        0 & 1
    \end{pmatrix}\,,\\
    A^{(N)}_0 &= \begin{pmatrix}
        1\\0
    \end{pmatrix}\,,\quad\quad
    A^{(N)}_1 = \begin{pmatrix}
        0\\ 1
    \end{pmatrix}\,,
\end{align}$$
where $k=2,3,...,N-1$.

In [10]:
N = 5

sites = siteinds("Qubit", N)

# Create all link indices first
links = [Index(2, "Link,l=$i") for i in 1:N-1]

# Create tensor by hand

# Site 1
A1 = ITensor(sites[1], links[1])
A1[sites[1] => 1, links[1] => 1] = 1/√2  # |0⟩ → bond 1
A1[sites[1] => 2, links[1] => 2] = 1/√2  # |1⟩ → bond 2
tensors = [A1]

# Middle sites
for i in 2:N-1
    A = ITensor(sites[i], links[i-1], links[i])
    A[sites[i] => 1, links[i-1] => 1, links[i] => 1] = 1.0
    A[sites[i] => 2, links[i-1] => 2, links[i] => 2] = 1.0
    push!(tensors, A)
end

# Last site
AN = ITensor(sites[N], links[N-1])
AN[sites[N] => 1, links[N-1] => 1] = 1.0
AN[sites[N] => 2, links[N-1] => 2] = 1.0
push!(tensors, AN)

# Create MPS from tensors
ghz = MPS(tensors)

MPS
[1] ((dim=2|id=404|"Qubit,Site,n=1"), (dim=2|id=465|"Link,l=1"))
[2] ((dim=2|id=980|"Qubit,Site,n=2"), (dim=2|id=465|"Link,l=1"), (dim=2|id=642|"Link,l=2"))
[3] ((dim=2|id=765|"Qubit,Site,n=3"), (dim=2|id=642|"Link,l=2"), (dim=2|id=38|"Link,l=3"))
[4] ((dim=2|id=72|"Qubit,Site,n=4"), (dim=2|id=38|"Link,l=3"), (dim=2|id=438|"Link,l=4"))
[5] ((dim=2|id=85|"Qubit,Site,n=5"), (dim=2|id=438|"Link,l=4"))


In [11]:
linkdims = [dim(linkind(ghz, i)) for i in 1:N-1]


4-element Vector{Int64}:
 2
 2
 2
 2

In [12]:
productMPS(sites, ["0", "0", "0", "0", "0"])

MPS
[1] ((dim=2|id=404|"Qubit,Site,n=1"), (dim=1|id=135|"Link,l=1"))
[2] ((dim=1|id=135|"Link,l=1"), (dim=2|id=980|"Qubit,Site,n=2"), (dim=1|id=282|"Link,l=2"))
[3] ((dim=1|id=282|"Link,l=2"), (dim=2|id=765|"Qubit,Site,n=3"), (dim=1|id=171|"Link,l=3"))
[4] ((dim=1|id=171|"Link,l=3"), (dim=2|id=72|"Qubit,Site,n=4"), (dim=1|id=592|"Link,l=4"))
[5] ((dim=1|id=592|"Link,l=4"), (dim=2|id=85|"Qubit,Site,n=5"))


In [13]:
expect(ghz, "Z")

5-element Vector{Float64}:
 -2.2371143170757388e-17
 -2.2371143170757388e-17
 -2.2371143170757388e-17
 -2.2371143170757388e-17
 -2.2371143170757388e-17

In [14]:
expect(ghz, "X")

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [15]:
println("⟨00000|GHZ⟩ = ", inner(productMPS(sites, ["Up", "Up", "Up", "Up", "Up"]), ghz))

⟨00000|GHZ⟩ = 0.7071067811865475


In [16]:
# Check amplitudes
println("⟨00000|GHZ⟩ = ", inner(MPS(sites, ["0", "0", "0", "0", "0"]), ghz))
println("⟨11111|GHZ⟩ = ", inner(MPS(sites, ["1", "1", "1", "1", "1"]), ghz))
println("⟨01000|GHZ⟩ = ", inner(MPS(sites, ["0", "1", "0", "0", "0"]), ghz))

⟨00000|GHZ⟩ = 0.7071067811865475
⟨11111|GHZ⟩ = 0.7071067811865475
⟨01000|GHZ⟩ = 0.0


In [17]:
function make_ghz_mps(sites)
    
    N = length(sites)
    
    # Create all link indices first
    links = [Index(2, "Link,l=$i") for i in 1:N-1]
    
    # Create tensor by hand
    
    # Site 1
    A1 = ITensor(sites[1], links[1])
    A1[sites[1] => 1, links[1] => 1] = 1/√2  # |0⟩ → bond 1
    A1[sites[1] => 2, links[1] => 2] = 1/√2  # |1⟩ → bond 2
    tensors = [A1]
    
    # Middle sites
    for i in 2:N-1
        A = ITensor(sites[i], links[i-1], links[i])
        A[sites[i] => 1, links[i-1] => 1, links[i] => 1] = 1.0
        A[sites[i] => 2, links[i-1] => 2, links[i] => 2] = 1.0
        push!(tensors, A)
    end
    
    # Last site
    AN = ITensor(sites[N], links[N-1])
    AN[sites[N] => 1, links[N-1] => 1] = 1.0
    AN[sites[N] => 2, links[N-1] => 2] = 1.0
    push!(tensors, AN)
    
    # Create MPS from tensors
    ghz = MPS(tensors)
    return ghz
    
end
    

make_ghz_mps (generic function with 1 method)

## 2. Matrix Product Operator

In [18]:
N = 5

sites = siteinds("Qubit", N)

os = OpSum()
os .+= "Z", 5

MPO(os, sites)

MPO
[1] ((dim=2|id=457|"Link,l=1"), (dim=2|id=9|"Qubit,Site,n=1")', (dim=2|id=9|"Qubit,Site,n=1"))
[2] ((dim=2|id=457|"Link,l=1"), (dim=2|id=768|"Link,l=2"), (dim=2|id=870|"Qubit,Site,n=2")', (dim=2|id=870|"Qubit,Site,n=2"))
[3] ((dim=2|id=768|"Link,l=2"), (dim=2|id=109|"Link,l=3"), (dim=2|id=269|"Qubit,Site,n=3")', (dim=2|id=269|"Qubit,Site,n=3"))
[4] ((dim=2|id=109|"Link,l=3"), (dim=2|id=717|"Link,l=4"), (dim=2|id=728|"Qubit,Site,n=4")', (dim=2|id=728|"Qubit,Site,n=4"))
[5] ((dim=2|id=717|"Link,l=4"), (dim=2|id=326|"Qubit,Site,n=5")', (dim=2|id=326|"Qubit,Site,n=5"))


In [19]:
function make_X_mpo(sites, i)
    os = OpSum()
    os .+= "X", i          # Add Pauli X on site i
    return MPO(os, sites)
end

function make_Z_mpo(sites, i)
    os = OpSum()
    os .+= "Z", i          # Add Pauli Z on site i
    return MPO(os, sites)
end

# correlation/parity
function make_ZZ_mpo(sites, i, j)
    os = OpSum()
    os .+= "Z", i, "Z", j  # Add Z_i * Z_j term
    return MPO(os, sites)
end

make_ZZ_mpo (generic function with 1 method)

In [20]:
ghz = make_ghz_mps(sites)

for i in 1:N
    println("< X$i > = ", inner(ghz', make_X_mpo(sites, i), ghz))
end

< X1 > = 0.0
< X2 > = 0.0
< X3 > = 0.0
< X4 > = 0.0
< X5 > = 0.0


In [21]:
ghz = make_ghz_mps(sites)

for i in 1:N
    println("< Z$i > = ", inner(ghz', make_Z_mpo(sites, i), ghz))
end

< Z1 > = 0.0
< Z2 > = 0.0
< Z3 > = 0.0
< Z4 > = 0.0
< Z5 > = 0.0


In [22]:
ghz = make_ghz_mps(sites)

for i in 1:N
    for j in 1:N
        println("< Z$i Z$j > = ", inner(ghz', make_ZZ_mpo(sites, i, j), ghz))
    end
end

< Z1 Z1 > = 0.9999999999999998
< Z1 Z2 > = 0.9999999999999998
< Z1 Z3 > = 0.9999999999999998
< Z1 Z4 > = 0.9999999999999998
< Z1 Z5 > = 0.9999999999999998
< Z2 Z1 > = 0.9999999999999998
< Z2 Z2 > = 0.9999999999999998
< Z2 Z3 > = 0.9999999999999998
< Z2 Z4 > = 0.9999999999999998
< Z2 Z5 > = 0.9999999999999998
< Z3 Z1 > = 0.9999999999999998
< Z3 Z2 > = 0.9999999999999998
< Z3 Z3 > = 0.9999999999999998
< Z3 Z4 > = 0.9999999999999998
< Z3 Z5 > = 0.9999999999999998
< Z4 Z1 > = 0.9999999999999998
< Z4 Z2 > = 0.9999999999999998
< Z4 Z3 > = 0.9999999999999998
< Z4 Z4 > = 0.9999999999999998
< Z4 Z5 > = 0.9999999999999998
< Z5 Z1 > = 0.9999999999999998
< Z5 Z2 > = 0.9999999999999998
< Z5 Z3 > = 0.9999999999999998
< Z5 Z4 > = 0.9999999999999998
< Z5 Z5 > = 0.9999999999999998


## 3. Entanglement entropy

In [66]:
# entropy of entanglement can be obtained from SVD

function entropy_bond(psi)
    N = length(psi)
    S_values = zeros(N-1)
    for n in 1:N-1
        # put orthogonality center on bond n
        orthogonalize!(psi, n)
        # SVD of site n tensor
        A = psi[n]
        U, S, V = svd(A, (siteinds(psi, n)))
        s = storage(S)
        p = s.^2
        p = p[p .> 1e-14]   # remove numerical zeros
        S_values[n] = -sum(p .* log2.(p))
    end
    return S_values
end


function entropy_2_sites(psi) 
    N = length(psi)
    S_values = zeros(N-1)
    for n in 1:N-1
        orthogonalize!(psi, n)
        if n == 1
            Linds = (siteinds(psi, n), siteinds(psi, n+1))
        else
            Linds = (linkind(psi, n), siteinds(psi, n), siteinds(psi, n+1))
        end
        _, S, _ = svd(psi[n] * psi[n+1], Linds)
        Svals = storage(S)
        p_values = Svals .^ 2
        p_values = filter(x -> x > 0, p_values)
        S_values[n] = -sum(p_values .* log2.(p_values))
    end
    return S_values
end

entropy_2_sites (generic function with 1 method)

In [24]:
N = 10

sites = siteinds("S=1/2", N)

states = [isodd(n) ? "Up" : "Dn" for n=1:N]

psi = productMPS(sites, states)

linkdims = [dim(linkind(rand_psi, i)) for i in 1:N-1]

println(linkdims)

entropy_bond(psi)
# entropy_2_sites(psi)

[20, 20, 20, 20, 20, 16, 8, 4, 2]


9-element Vector{Float64}:
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0

In [25]:
N = 10

sites = siteinds("Qubit", N)

ghz = make_ghz_mps(sites)

linkdims = [dim(linkind(rand_psi, i)) for i in 1:N-1]

println(linkdims)

entropy_bond(ghz)
# entropy_2_sites(psi)

[20, 20, 20, 20, 20, 16, 8, 4, 2]


9-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
N = 10

sites = siteinds("Qubit", N)

rand_psi = randomMPS(sites; linkdims=10)

linkdims = [dim(linkind(rand_psi, i)) for i in 1:N-1]

println(linkdims)

entropy_bond(rand_psi)
# entropy_2_sites(psi)

[10, 10, 10, 10, 10, 10, 8, 4, 2]


9-element Vector{Float64}:
 0.9001040398510158
 0.8993306647255086
 0.9980617159945141
 0.9943073263654714
 0.9846123604669028
 0.9990094007879309
 0.9950359928505325
 0.98339060418864
 0.9992377557235368

In [27]:
entropy_2_sites(rand_psi)

9-element Vector{Float64}:
 1.6766704090044569
 1.7342481887364902
 1.9676185720206094
 1.93276407596143
 1.9039388866357363
 1.9770154900473647
 1.9370548134624235
 1.9585322869336572
 1.9024282999503501

## Some exercises

Q1. Implement the W state with MPS and check to see if its amplitude is correct. Alternatively show it consistently produces an eigenvalue of 1 for the number operator $n_i=|1\rangle \langle 1| = (1-Z_i)/2$.

Q2. Compute the coherence operator $C$ for the GHZ state and show it gives 1 for the true GHZ state.

$$C=|000\rangle\langle 111|+|111\rangle\langle 000|$$
